package mgr;

public class mapa extends javax.swing.JPanel {

    private int skalaProc = 100;           // 100%
    private double widok_x = 0;
    private double widok_y = 0;

    private int prevMouseX, prevMouseY;

    public mapa() {
        initComponents();

        java.awt.event.MouseAdapter ma = new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                prevMouseX = e.getX();
                prevMouseY = e.getY();
            }

            @Override
            public void mouseDragged(java.awt.event.MouseEvent e) {
                int dx = e.getX() - prevMouseX;
                int dy = e.getY() - prevMouseY;
                widok_x += dx;
                widok_y += dy;
                prevMouseX = e.getX();
                prevMouseY = e.getY();
                repaint();
            }

            @Override
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent e) {
                int notches = e.getWheelRotation(); // >0 w dół (oddal), <0 w górę (przybliż)
                int oldProc = skalaProc;

                // krok = 10% bieżącej skali
                int step = (int) Math.round(skalaProc * 0.1);
                if (step < 1) {
                    step = 1; // zabezpieczenie, żeby zawsze coś się zmieniało
                }
                skalaProc += -notches * step;   // kółko w górę -> +skala, w dół -> -skala
                skalaProc = Math.max(10, Math.min(500, skalaProc)); // zakres 10%–500%

                if (skalaProc != oldProc) {
                    double sOld = oldProc / 100.0;
                    double sNew = skalaProc / 100.0;
                    double factor = sNew / sOld;

                    // utrzymaj punkt pod kursorem
                    double cx = e.getX();
                    double cy = e.getY();
                    widok_x = cx - factor * (cx - widok_x);
                    widok_y = cy - factor * (cy - widok_y);

                    repaint();
                }
            }
        };
        addMouseListener(ma);
        addMouseMotionListener(ma);
        addMouseWheelListener(ma);
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);

        java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;

        // zastosuj przesunięcie i skalę
        g2d.translate(widok_x, widok_y);
        g2d.scale(skalaProc / 100.0, skalaProc / 100.0);

        int r = 100;
        g2d.setColor(java.awt.Color.RED);
        // okrąg na środku panelu (współrzędne liczone od rozmiaru panelu)
        g2d.drawOval(getWidth() / 2 - r, getHeight() / 2 - r, 2 * r, 2 * r);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
