/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mgr;

import java.util.List;

/**
 *
 * @author Michal
 */
public class oknoMapy extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(oknoMapy.class.getName());

    public oknoMapy() {
        initComponents();
        System.out.println("otwarto okno mapy");
        setExtendedState(Main.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapa1 = new mgr.mapa();
        jPanel1 = new javax.swing.JPanel();
        LabelPktStart = new javax.swing.JLabel();
        LabelPktEnd = new javax.swing.JLabel();
        wybierzPktStart = new javax.swing.JButton();
        wybierzPktKoniec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapa1.setPreferredSize(new java.awt.Dimension(1000, 675));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelPktStart.setBackground(new java.awt.Color(0, 0, 0));
        LabelPktStart.setText("start");

        LabelPktEnd.setBackground(new java.awt.Color(0, 0, 0));
        LabelPktEnd.setText("end");

        wybierzPktStart.setText("Wybierz punkt początkowy:");
        wybierzPktStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wybierzPktStartActionPerformed(evt);
            }
        });

        wybierzPktKoniec.setText("Wybierz punkt końcowy:");
        wybierzPktKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wybierzPktKoniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wybierzPktStart)
                    .addComponent(wybierzPktKoniec))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPktEnd)
                    .addComponent(LabelPktStart))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPktStart)
                    .addComponent(wybierzPktStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPktEnd)
                    .addComponent(wybierzPktKoniec))
                .addGap(15, 15, 15))
        );

        jButton1.setText("start ALGGEN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("start DIJKSTRA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(mapa1, javax.swing.GroupLayout.DEFAULT_SIZE, 1721, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mapa1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wybierzPktKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wybierzPktKoniecActionPerformed
        // TODO add your handling code here:

        Wezel zaznaczony = mapa1.ZaznaczonyWezel;
        DANE.wezelKoncowyAlgorytmu = zaznaczony;

        this.LabelPktEnd.setText("" + zaznaczony.ID);

        if (DANE.wezelKoncowyAlgorytmu.ID == DANE.wezelStartowyAlgorytmu.ID) {
            DANE.wezelStartowyAlgorytmu = new Wezel();
            this.LabelPktStart.setText("");
        }
    }//GEN-LAST:event_wybierzPktKoniecActionPerformed

    private void wybierzPktStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wybierzPktStartActionPerformed
        // TODO add your handling code here:

        Wezel zaznaczony = mapa1.ZaznaczonyWezel;
        DANE.wezelStartowyAlgorytmu = zaznaczony;

        this.LabelPktStart.setText(zaznaczony.ID + "");

        if (DANE.wezelKoncowyAlgorytmu.ID == DANE.wezelStartowyAlgorytmu.ID) {
            DANE.wezelKoncowyAlgorytmu = new Wezel();
            this.LabelPktEnd.setText("");
        }
    }//GEN-LAST:event_wybierzPktStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ALGGEN alg = new ALGGEN();
        alg.startAlg();

        mapa1.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        ALGDIJKSTRA algdij = new ALGDIJKSTRA();

        System.out.println("Koszt do konca: " + algdij.getKosztDoKonca());
        DANE.ALG_GEN_SCIEZKA = algdij.getSciezkaDrog();
        System.out.println();
        for (Droga droga : DANE.ALG_GEN_SCIEZKA) {
            System.out.println(droga.ID);
        }
        mapa1.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new oknoMapy().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPktEnd;
    private javax.swing.JLabel LabelPktStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private mgr.mapa mapa1;
    private javax.swing.JButton wybierzPktKoniec;
    private javax.swing.JButton wybierzPktStart;
    // End of variables declaration//GEN-END:variables
}
